[package]
name = "agent-jni"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
agent-core = { version = "0.1.0", path = "../agent-core" }
agent-llm-anthropic = { version = "0.1.0", path = "../agent-llm-anthropic" }
agent-store-fs = { version = "0.1.0", path = "../agent-store-fs" }
async-trait.workspace = true
base64 = "0.23.0"
jni = "0.21"
serde_json.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }

[lib]
crate-type = ["cdylib", "rlib"]
