[package]
name = "agent-llm-openai"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
agent-core = { version = "0.1.0", path = "../agent-core" }
async-trait.workspace = true
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json", "native-tls"] }

[target.'cfg(not(windows))'.dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
